language: go
os:
    - linux
    - osx
go:
    - 1.7.x
install:
    - go get -v github.com/Masterminds/glide
    - cd $GOPATH/src/github.com/Masterminds/glide && go install && cd -
    - glide install
    - mkdir -p $TRAVIS_BUILD_DIR/vendor/branches-health/ && cp -r $TRAVIS_BUILD_DIR/core $TRAVIS_BUILD_DIR/vendor/branches-health/
script:
    - go build
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: WZdYs0WGnKvN7dcG1W52K0EF1lShlPlrAp0dsnZ0rRE03xOphEl4HHNPrKDyaareUzZODX2CmB8Gz3K0Kb+GGO0WTQNP/SNwl5Eh1fCkW8ODFQkSqu6C6o/zE2EnE+goPGrCA4wdYhZHEM3PqTCjHVzpZQsAYPOweCaji7tLENd9k4mHkfm0dm8tYz0CcSPHH0E8IFWAxB78+oVftI6D6VziPhhmwpeTNM4qTUH2kDHWFWSlTv5RC5FyfbhXraa2ta2/k4AbyjhEc9EZK3dX1dxCSUhfoddepc8DpdO0O+4/Mdxl3ieLLJj/0i94sYxg/W4xw13t/Dbtq350bXvupzCiksCMBcYverDER70dToeHqdWFmJXX3hB+f0qTZjvY3BzfQ/kXD0sEuseRqmjpPWScJL8laxKjzqqiFpwI44prbnhJByxp/P6oWuL8rQlgYpqkrvJyXa90SgYkj1kkH2Qzxc/tbosZfthR/PGyVq58E0Mg9fMx3F4LPnIEocAcz1fiwEiy8+CnrH1KSfb1+O06c5nPHsGWeAy6h+V3UQChDf2DmChzLsdVU501c7S86LoY8stAMrm6OYq0fy2U50i6Sc9JVcwivK3kCvcB5FI10PoxxPQvQNySs5D7y41lrJMdf3dC8Gf70zUsgKKTe4FknohTV57+0xVBHlXJM9Q=
  file:
    - branches-health
  on:
    repo: idooo/branches-health
